package com.purbayan.readifybackend.entity;

import lombok.Data;

import javax.persistence.*;

/**
 * The Book entity represents a book in the system.
 *
 * It is marked as a JPA entity, meaning that it maps to a table in a database.
 */
@Entity
@Table(name = "book")
@Data
public class Book {

    /**
     * The unique identifier for this book.
     *
     * It is marked as the primary key for the database table and is automatically
     * generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * The title of this book.
     *
     * It maps to a column in the database table named "title".
     */
    @Column(name = "title")
    private String title;

    /**
     * The description of this book.
     *
     * It maps to a column in the database table named "description".
     */
    @Column(name = "description")
    private String description;

    /**
     * The total number of copies of this book.
     *
     * It maps to a column in the database table named "copies".
     */
    @Column(name = "copies")
    private int copies;

    /**
     * The number of copies of this book that are currently available.
     *
     * It maps to a column in the database table named "copiesAvailable".
     */
    @Column(name = "copiesAvailable")
    private int copiesAvailable;

    /**
     * The category of this book.
     *
     * It maps to a column in the database table named "category".
     */
    @Column(name = "category")
    private String category;

    /**
     * The URL of an image representing this book.
     *
     * It maps to a column in the database table named "img".
     */
    @Column(name = "img")
    private String img;
}
