package com.purbayan.readifybackend.entity;

import lombok.Data;
import javax.persistence.*;

@Entity // Marks this class as a JPA entity
@Table(name = "book") // Specifies the name of the database table that this entity maps to
@Data // Generates getter and setter methods for all fields, as well as a toString method
public class Book {

    @Id // Marks this field as the primary key for the database table
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key value is generated by the database itself
    @Column(name = "id") // Specifies the name of the column in the database table that maps to this field
    private Long id;

    @Column(name = "title") // Specifies the name of the column in the database table that maps to this field
    private String title;

    @Column(name = "description") // Specifies the name of the column in the database table that maps to this field
    private String description;

    @Column(name = "copies") // Specifies the name of the column in the database table that maps to this field
    private int copies;

    @Column(name = "copiesAvailable") // Specifies the name of the column in the database table that maps to this field
    private int copiesAvailable;

    @Column(name = "category") // Specifies the name of the column in the database table that maps to this field
    private String category;

    @Column(name = "img") // Specifies the name of the column in the database table that maps to this field
    private String img;
}
