package com.purbayan.readifybackend.entity;

import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.util.Date;

/**
 * The Book entity represents a review in the system.
 *
 * It is marked as a JPA entity, meaning that it maps to a table in a database.
 */
@Entity
@Table(name = "review")
@Data
public class Review {

    /**
     * The unique identifier for this book.
     *
     * It is marked as the primary key for the database table and is automatically
     * generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * The user_email of the user.
     *
     * It maps to a column in the database table named "user_email".
     */
    @Column(name = "user_email")
    private String userEmail;

    /**
     * The date of the review.
     *
     * It maps to a column in the database table named "review".
     */
    @Column(name = "date")
    @CreationTimestamp
    private Date date;

    /**
     * The rating of this review.
     *
     * It maps to a column in the database table named "rating".
     */
    @Column(name = "rating")
    private double rating;

    /**
     * The id of this book.
     *
     * It maps to a column in the database table named "book_id".
     */
    @Column(name = "book_id")
    private Long bookId;

    /**
     * The description  of this book review.
     *
     * It maps to a column in the database table named "review_description".
     */
    @Column(name = "review_description")
    private String reviewDescription;
}
